version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASSWORD: "yelp-dockerhub:password"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo login to dockerhub
      - echo "$DOCKERHUB_PASSWORD" | docker login --username sloppynetworks --password-stdin
      - echo Installing node modules

      # - echo parameter value is $REACT_URL
      # - echo "parameter value is $REACT_URL"
      - npm install
  build:
    commands:
      - echo Running tests
      - npm run test
